backend:
  name: proxy
  login: /.netlify/functions/auth
  proxy_url: /.netlify/functions/auth
  branch: main

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "wiki"
    label: "Wiki Entries"
    folder: "src/content/wiki"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Category", name: "category", widget: "select", options: ["spirits", "seals", "rituals", "concepts"] }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Summary", name: "summary", widget: "text" }
      - { label: "Related", name: "related", widget: "list" }
      - { label: "Body", name: "body", widget: "markdown" }
