collections:
  - name: "spirits"
    label: "Great Spirits"
    folder: "content/beliefs/spirits"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Seal", name: "seal", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "beliefs"
    label: "Beliefs"
    files:
      - label: "Beliefs Page"
        name: "beliefs"
        file: "content/beliefs/index.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
